spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contriess_dev
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
